# two services for the frontend and backend in ./frontend and ./backend directory
# frontend is vite-react and backend is fastAPI
version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8001:8001
